import React, { useMemo, useState, useEffect, useRef } from 'react'
import MessageList from './MessageList.jsx'
import MessageInput from './MessageInput.jsx'
import { chatWithToolsStream } from '../api.js'
import InstanceEditor from './InstanceEditor.jsx'
import Dashboard from './Dashboard.jsx'

// What would you like to explore next?
const COVERAGE_QUESTIONS = {
  local: {
    tellsYou: [
      "What factors lowered/increased my score?",
      "How much did a factor affect my score?",
    ],
    doesntTellYou: [
      "What can I do to improve my score to 50?",
      "Which factors are generally important across all applicants?",
      "How would my score change if I have fewer loans?",
    ]
  },
  counterfactual: {
    tellsYou: [
      "What is the smallest change needed to get approved?",
    ],
    doesntTellYou: [
      "Why was my original score so low?",
      "Would decreasing my credit usage alone increase my score?",
      "Did my \"Loans not paid off\" negatively affect my score?"
    ]
  },
  global: {
    tellsYou: [
      "Which factors matter the most to the system in general?",
      "Does the system generally prioritise late payments or credit usage?",
    ],
    doesntTellYou: [
      "What changes should I make to increase my score?",
      "Why was my specific application denied?",
      "How much did \"credit used\" impact my score?",
    ]
  },
  cp: {
    tellsYou: [
      "What happens to my score if I change just one factor?",
      "How strongly does my score react to a specific factor?"
    ],
    doesntTellYou: [
      "Which factor affected my current score the most?",
      "Did a factor positively affect the score I got?",
      "What is the smallest change needed to get approved?",
    ]
  }
}

const DESIGN_C_QUESTIONS = {
  local: {
    tellsYou: [
      "Which factor had the biggest impact on the applicant's current score?",
      "Did the applicant's credit used positively influenced their current score?",
    ],
    doesntTellYou: [
      "How would the applicant's score change if they had more loans?",
      "What changes can the applicant make to improve their score to 50?",
      "Which factors are generally important across all applicants?",
    ]
  },
  cp: {
    tellsYou: [
      "How would the applicant's score change if they had more loans?",
      "How strongly does this applicant's score react to a specific factor?"
    ],
    doesntTellYou: [
      "Did the applicant's credit used positively influenced their current score?",
      "Which factor had the biggest impact on the applicant's current score?",
      "For other applicants, does increasing on-time payment rate increases their score?",
    ]
  }
}

// Dictionary to unify explanation labels for both the System Prompt and the UI Prompts
const EXPLANATION_DICT = {
  local: {
    system: "Which factors pushed the applicant's score up or down. Generated by starting from a baseline score for the average applicant and attributing the difference between that baseline and this applicant's predicted score across the applicant's factors",
    ui: "What Affected Your Score",
    description: "how each factor influenced the score this applicant got. Blue bars represent factors that increased the score. Red bars represent factors that decreased the score"
  },
  counterfactual: {
    system: "Smallest set of changes needed for this applicant to reach target score. Generated by searching for a nearby combination of factor changes that makes the model reach the target. This is not a ranking of feature importance or proof that unchanged factors do not matter.",
    ui: "How to Improve Your Score",
    description: "the smallest change this applicant need to make to reach the target score"
  },
  cp: {
    system: "How this applicant's predicted score will change when changing a single factor. Generated by keeping all other factor values fixed at the applicant's current values and repeatedly predicting the score at hypothetical values of the selected factor. It is not a local-importance chart: it cannot say whether the factor helped or hurt the current score, or rank it against other factors.",
    ui: "How Each Factor Affects Your Score",
    description: "how changing one factor at a time would change this applicant's score"
  },
  // global: {
  //   system: "Which factors matter the most across everyone",
  //   ui: "What Mattered Most Overall",
  //   description: "how important each factor is across all applicants"
  // },
}

// Helper to dynamically generate the welcome message based on the selected explanation
const generateWelcomeMessage = (explanationKey) => {
  if (!explanationKey) {
    return "The dashboard currently displays no explanation. Please select an explanation from the menu to begin.";
  }
  const info = EXPLANATION_DICT[explanationKey];
  return `The dashboard currently displays **${info.ui}**, which shows ${info.description}. Type in any questions you may have.`;
};

// Helper to read initial explanation from URL parameters
const getInitialExplanation = () => {
  if (typeof window !== "undefined") {
    const params = new URLSearchParams(window.location.search);
    const exp = params.get("exp");
    if (exp && EXPLANATION_DICT[exp]) {
      return exp;
    }
  }
  return "local"; // Default to "What Affected Your Score"
};

// Helper to read the applicant instance ID from URL parameters
const getInitialInstanceId = () => {
  if (typeof window !== "undefined") {
    const params = new URLSearchParams(window.location.search);
    const id = params.get("id"); // e.g., ?id=58
    if (id && !isNaN(parseInt(id, 10))) {
      return parseInt(id, 10);
    }
  }
  return 12; // Default ID
};

const getParticipantId = () => {
  if (typeof window !== "undefined") {
    const params = new URLSearchParams(window.location.search);
    return params.get("pid") || "anonymous_user";
  }
  return "anonymous_user";
};

const getRequiredQuestions = () => {
  if (typeof window !== "undefined") {
    const params = new URLSearchParams(window.location.search);
    const req = params.get("req");
    if (req && !isNaN(parseInt(req, 10))) {
      return parseInt(req, 10);
    }
  }
  return 5;
};


export default function ChatPage() {
  // Initialize instance ID from URL
  const [userInstanceId] = useState(getInitialInstanceId())
  const [participantId] = useState(getParticipantId());
  
  // Set required questions to 8 directly
  const [requiredQuestions] = useState(getRequiredQuestions());
  const [showManual, setShowManual] = useState(false)
  const applicantNames = { 57: "Alex", 58: "Bob" };
  const applicantName = applicantNames[userInstanceId];
  const applicantReference = applicantName
    ? `applicant ID ${userInstanceId} (${applicantName})`
    : `applicant ID ${userInstanceId}`;

  // Set selected explanation from URL or default to 'local'
  const [selectedExplanation, setSelectedExplanation] = useState(getInitialExplanation())

  // Track whether the explanations menu is collapsed or expanded
  // const [showExplanationsMenu, setShowExplanationsMenu] = useState(true)

  // Track which Design C and Design B questions have been clicked
  const [clickedQuestions, setClickedQuestions] = useState(new Set())

  // Initialise with the welcome message of the starting explanation
  const [messages, setMessages] = useState([
    {
      role: 'assistant',
      content: generateWelcomeMessage(getInitialExplanation())
    }
  ])

  const [busy, setBusy] = useState(false)
  const [visualisations, setVisualisations] = useState([])
  const [counterfactualViz, setCounterfactualViz] = useState(null)
  const [cpVisualisations, setCpVisualisations] = useState([])
  const [backendHistory, setBackendHistory] = useState([])
  const [showSuggestions, setShowSuggestions] = useState(true)

  // State to track if the input box is focused to show/hide suggestions
  const [isInputFocused, setIsInputFocused] = useState(false)

  const activeDesign = "C" // Hardcoded to C as default

  // Dynamically compile Design C "tells you" questions 
  const activeDesignCTellsYou = useMemo(() => {
    if (!selectedExplanation || !DESIGN_C_QUESTIONS[selectedExplanation]?.tellsYou) return [];
    return DESIGN_C_QUESTIONS[selectedExplanation].tellsYou;
  }, [selectedExplanation]);

  // Dynamically compile Design C "doesn't tell you" questions 
  const activeDesignCDoesntTellYou = useMemo(() => {
    if (!selectedExplanation || !DESIGN_C_QUESTIONS[selectedExplanation]?.doesntTellYou) return [];
    return DESIGN_C_QUESTIONS[selectedExplanation].doesntTellYou;
  }, [selectedExplanation]);

  // --- QUALTRICS TRACKING LOGIC ---
  // Simply count how many total messages the user has sent
  const totalUserQuestions = messages.filter(m => m.role === 'user').length;
  const additionalQuestionsLeft = Math.max(0, requiredQuestions - totalUserQuestions);
  
  // The requirement is met solely if they have asked 8 questions
  const isRequirementMet = totalUserQuestions >= requiredQuestions;

  useEffect(() => {
    // If embedded in an iframe (Qualtrics), send a message when requirement is met
    if (isRequirementMet) {
      window.parent.postMessage({ type: "CHAT_REQUIREMENT_MET" }, "*");
    }
  }, [isRequirementMet]);
  // ---------------------------------

  // Keep a ref of the selected explanation to safely access inside async callbacks
  const selectedExpRef = useRef(selectedExplanation)
  useEffect(() => {
    selectedExpRef.current = selectedExplanation
  }, [selectedExplanation])

  // Update the initial message if the user clicks/toggles dashboard explanations BEFORE asking a question
  /*
  useEffect(() => {
    setMessages(prev => {
      const hasUserMsg = prev.some(m => m.role === 'user');
      if (hasUserMsg) return prev;
      return [{ role: 'assistant', content: generateWelcomeMessage(selectedExplanation) }];
    });
  }, [selectedExplanation]);
  */

  // Start a new log session on initial page load / refresh
  useEffect(() => {
    // You can append the PID so your backend saves logs with the Prolific ID
    fetch(`http://127.0.0.1:5001/api/session/reset?pid=${participantId}`)
      .then(res => res.json())
      .then(data => console.log("Initial session started for:", participantId, data.log_file))
      .catch(err => console.error("Error starting session:", err));
  }, [participantId]);

  const visibleTexts = useMemo(() => {
    if (!selectedExplanation) {
      return {
        system: "No explanations currently visible",
        ui: "no explanation"
      }
    }
    return {
      system: EXPLANATION_DICT[selectedExplanation].system,
      ui: EXPLANATION_DICT[selectedExplanation].ui
    }
  }, [selectedExplanation])

  // The system prompt dynamically reads the current dashboard state.
  const system = useMemo(() => {
    return `You are a helpful assistant explaining a machine learning model used as an automated tool to approve or decline credit limit increase applications. The user is viewing the applicant identified as ${applicantReference} in the dataset. Assume the user has no prior knowledge of AI. When answering questions, assume the user is asking about this applicant's specific profile unless stated otherwise. The model predicts each applicant a credit score from 0 to 100. A score of 50 or higher means the application is approved.

      The model considers these six factors/features:
      - Credit used (%) -- Percentage of available credit already used        
      - Months since last late payment -- How long since they last missed a payment
      - On-time payment rate (%) -- How often they've paid on time
      - Number of loans -- Number of loan accounts they've had
      - Loans not paid off (%) -- How many borrowing accounts still have debt on them
      - Months since last credit application -- How long since they last applied for credit
      
      Currently, the user only has the following explanation visible on the dashboard on the left: ${visibleTexts.ui} (${visibleTexts.system}). 
      Whenever the user refers to "this explanation", "this chart", or "this figure", ALWAYS interpret it as the currently visible ${visibleTexts.ui} panel.   
      IMPORTANT: You do NOT automatically know the data behind the explanation. You MUST call the corresponding tool(s) to retrieve the data for this visible explanation so you can accurately understand the outputs and answer the user's questions. 

      FOR EVERY USER QUESTION, FOLLOW THIS WORKFLOW
      Step 1. Identify the user's information need.

      Determine what the user is actually trying to learn (for example:
      - understand why the model made this decision
      - understand which factors mattered most
      - understand what changes would improve their score
      - understand the model's general behaviour
      ).

      Step 2. Evaluate whether the CURRENTLY DISPLAYED explanation ${visibleTexts.ui} can answer the question.

      Ask yourself:
      "Can this explanation directly answer the user's question based on how it is generated?"

      If YES:
      - Explicitly state that your answer is based on the currently displayed ${visibleTexts.ui} explanation, and why this explanation can answer the question.
      - Call the corresponding tool if its underlying data is required, Answer using only information supported by that explanation.

      If NO:
      You MUST do ALL of the following:
      (1) Explain why the displayed explanation cannot answer the question by referring to limitations of the explanation generation process (e.g., what the explanation captures, omits, or assumes). Do NOT simply state that it is the wrong explanation or that the information is missing.

      Examples:
      - "This explanation is generated by attributing the model's current prediction to the contribution of each feature. Because it only describes why this prediction was made, it cannot determine how the prediction would change under a different feature value."
      - "This explanation is generated to explain a single prediction for this applicant. Because it captures local decision factors rather than patterns learned across the full population, it cannot describe general trends across all applicants."
      - "This explanation shows the relative influence of features on one's prediction rather than the causal effect of changing them, it cannot recommend what action the applicant should take."

      (2) State the assumption or scope of the current explanation.

      For example:
      - It ranks feature contributions.
      - It is descriptive rather than hypothetical.
      - It is local rather than global.

      (3) Immediately call the correct tool to generate the explanation that matches the user's question. Never stop after saying another explanation is needed. Always generate the appropriate explanation by calling the correct tool.

      (4) Explain the newly generated chart and answer the user's original question.

      Guidelines:
      - Be concise. Use layperson-friendly language. MUST answer in less than 150 words.
      - AVOID ADDED ADVICE: Do not invent financial advice, or hallucinate results. Only state relationships supported by the explanation or tool outputs. When users ask what they should change, describe changes only in terms of the model's behaviour, not real-world financial advice.
      - If required inputs (e.g., factor name, target) are missing, ask the user to provide them.
      - Clearly distinguish between advice for a single applicant versus a broader pattern across applicants.`
  }, [userInstanceId, applicantReference, visibleTexts.system, visibleTexts.ui])

  async function handleSend(text) {
    if (!text?.trim()) return

    setShowSuggestions(false)
    setIsInputFocused(false) // Hide suggestions after sending

    const userMsg = { role: "user", content: text }
    setMessages(prev => [...prev, userMsg])

    // streaming
    setBusy(true)
    setMessages(prev => [...prev, { role: "assistant", content: "" }])

    chatWithToolsStream({
      message: text,
      history: backendHistory,
      system,
      options: { temperature: 1 },
      onToken: token => {
        setMessages(prev => {
          const copy = [...prev]
          const last = copy[copy.length - 1]
          if (last?.role === "assistant") {
            last.content += token
          }
          return copy
        })
      },
      onVisualisations: vizs => {
        if (!vizs?.length) return

        const counterfactuals = []
        const cpDashboardVizs = []
        const inlineVizes = []

        vizs.forEach(v => {
          const tool = v?.meta?.tool || v?.visualisation?.meta?.tool

          let vizType = "extra"
          if (tool === "get_counterfactual_explanation") vizType = "counterfactual"
          if (tool === "generate_shap_bar_plot" || tool === "generate_local_shap_bar_plot") vizType = "local"
          if (tool === "generate_shap_summary_plot") vizType = "global"

          // Separate single CP plots from the "All CP plots" view
          if (tool === "generate_all_cp_plots") vizType = "cp_dashboard"
          if (tool === "get_cp_plot") vizType = "single_cp_plot"

          if (vizType === "counterfactual") {
            counterfactuals.push(v)
          }
          else if (vizType === "cp_dashboard") {
            cpDashboardVizs.push(v)
          }

          // Determine what goes into the chat timeline (inline)
          if (
            vizType === "extra" ||
            vizType === "single_cp_plot" ||
            (vizType === "cp_dashboard" && selectedExpRef.current !== "cp") ||
            (vizType === "local" && selectedExpRef.current !== "local") ||
            (vizType === "global" && selectedExpRef.current !== "global") ||
            (vizType === "counterfactual" && selectedExpRef.current !== "counterfactual")
          ) {
            inlineVizes.push(v)
          }
        })

        if (counterfactuals.length > 0) {
          setCounterfactualViz(JSON.parse(JSON.stringify(counterfactuals[0])))
        }

        if (cpDashboardVizs.length > 0) {
          setCpVisualisations(cpDashboardVizs)
        }

        if (inlineVizes.length > 0) {
          setMessages(prev => {
            const copy = [...prev]
            const last = copy[copy.length - 1]
            if (last?.role === "assistant") {
              last.visualisations = last.visualisations
                ? [...last.visualisations, ...inlineVizes]
                : [...inlineVizes]
            }
            return copy
          })
        }
      },
      onDone: payload => {
        if (payload?.history) {
          setBackendHistory(payload.history)
        }
        setBusy(false)
      },
      onError: err => {
        setMessages(prev => [
          ...prev,
          {
            role: "assistant",
            content: `Error: ${JSON.stringify(err)}`,
          },
        ])
        setBusy(false)
      },
    })
  }

  const handleDesignCQuestion = (q, category) => {
    // Mark this exact question string as clicked
    setClickedQuestions(prev => new Set(prev).add(q))

    let promptText = ""
    if (category === "tellsYou") {
      promptText = `${q}`
    } else {
      promptText = `Explain briefly why the explanation "${visibleTexts.ui}" cannot answer my question: "${q}". Use the appropriate tool to generate the explanation that can answer it.`
    }

    handleSend(promptText)
  }

  const showInitialSuggestions =
    showSuggestions &&
    !busy &&
    messages.filter(m => m.role === "user").length === 0

  /*
  // Only allow setting the selection if it is currently empty.
  const handleSelectExplanation = (key) => {
    if (!selectedExplanation) {
      setSelectedExplanation(key)
    }
  }

  // Calculate unclicked Design B options
  const unclickedDesignBOptions = activeDesignBOptions?.filter(opt => !clickedQuestions.has(opt)) || [];
  */

  // Condition for showing the floating popup menu
  const showFloatingSuggestions = isInputFocused && activeDesign === "C" && !busy && selectedExplanation !== "" && (activeDesignCTellsYou.length > 0 || activeDesignCDoesntTellYou.length > 0);

  return (
    <div style={{ display: "flex", gap: 12, height: "100%", padding: 12 }}>

      {/* Left side: Instance editor, Dashboard */}
      <div
        style={{
          flex: 0.4,
          display: "flex",
          flexDirection: "column",
          gap: 10,
          minWidth: 400,
          paddingRight: 4 // slight breathing room before the chat
        }}
      >
        {/* Invisible spacer to perfectly match the height of the right-side Info button container */}
        <div style={{ height: "16px", flexShrink: 0 }}></div>

        {/* Instance Editor */}
        <div
          style={{
            border: "1px solid #ddd",
            borderRadius: 8,
            background: "#fafafa",
            overflow: "auto",
          }}
        >
          <InstanceEditor instanceId={userInstanceId} />
        </div>

        {/* Dashboard Section */}
        <div
          style={{
            flex: 1,
            minHeight: 0,
            display: "flex",
            flexDirection: "column",
          }}
        >
          <div style={{ overflow: "auto", flex: 1 }}>
            <Dashboard
              instanceId={userInstanceId}
              visualisations={visualisations}
              counterfactualViz={counterfactualViz}
              cpVisualisations={cpVisualisations}
              selectedExplanation={selectedExplanation}
            />
          </div>
        </div>
      </div>

      {/* Right side: Chat */}
      <div
        style={{
          flex: 0.6,
          display: "flex",
          flexDirection: "column",
          gap: 6,
          position: "relative",
        }}
      >
        {/* Help Button above the Chat Container */}
        <div style={{ display: "flex", justifyContent: "flex-end", alignItems: "center", height: "20px", flexShrink: 0 }}>
          <button
            onClick={() => setShowManual(true)}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "4px",
              background: "#f3f4f6",
              border: "1px solid #e5e7eb",
              borderRadius: "16px",
              padding: "2px 8px",
              fontSize: "13px",
              color: "#4b5563",
              cursor: "pointer",
              fontWeight: 600,
            }}
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="10"></circle>
              <line x1="12" y1="16" x2="12" y2="12"></line>
              <line x1="12" y1="8" x2="12.01" y2="8"></line>
            </svg>
            Info
          </button>
        </div>


        {/* Floating Design Switcher Buttons */}
        {/* 
        {showInitialSuggestions && (
          <div
            style={{
              position: "absolute",
              top: -42,
              left: "50%",
              transform: "translateX(-50%)",
              display: "flex",
              gap: 8,
              zIndex: 20
            }}
          >
            {["A", "B", "C"].map((design) => (
              <button
                key={design}
                onClick={() => setActiveDesign(design)}
                style={{
                  padding: "6px 16px",
                  borderRadius: 20,
                  border: "1px solid #cbd5e1",
                  background: activeDesign === design ? "#2563eb" : "#f8fafc",
                  color: activeDesign === design ? "white" : "#334155",
                  cursor: "pointer",
                  fontSize: 13,
                  fontWeight: 600,
                  transition: "all 0.2s ease"
                }}
              >
                Design {design}
              </button>
            ))}
          </div>
        )}
        */}

        {/* Chat Container */}
        <div
          style={{
            border: "1px solid #ddd",
            borderRadius: 8,
            flex: 1,
            background: "white",
            position: "relative",
            display: "flex",
            flexDirection: "column",
            overflow: "hidden" // Keeps children constrained inside the rounded borders
          }}
        >
          {/* Main Message History */}
          <div style={{ flex: 1, overflow: "auto", position: "relative", padding: 12 }}>
            <MessageList messages={messages} busy={busy} />

            {/* This spacer provides the empty room needed for the browser to scroll the latest message to the top */}
            <div style={{ height: "80vh", flexShrink: 0 }} />
          </div>

          {/* Input Area (now inside the same border, separated by a line) */}
          <div
            style={{
              borderTop: "1px solid #ddd", /* The dividing line */
              padding: "12px",
              display: "flex",
              flexDirection: "column",
              gap: 8,
              backgroundColor: "#fff", /* Not greyed out */
              position: "relative" /* Critical for the absolute floating box to anchor to this div */
            }}
            onFocus={() => setIsInputFocused(true)}
            onBlur={(e) => {
              // Delay hiding slightly so clicks on suggestions register before the element unmounts/fades
              setTimeout(() => setIsInputFocused(false), 200);
            }}
          >

            {/* Floating Suggested Question List (Floats above the input) */}
            <div style={{
              position: "absolute",
              bottom: "100%", // Place it right above the border line
              left: 0,
              right: 12,
              padding: "0 12px", // Matches the parent padding
              marginBottom: "8px", // Gap between float box and input box
              zIndex: 50,
              opacity: showFloatingSuggestions ? 1 : 0,
              pointerEvents: showFloatingSuggestions ? "auto" : "none",
              transform: showFloatingSuggestions ? "translateY(0)" : "translateY(10px)",
              transition: "all 0.2s cubic-bezier(0.16, 1, 0.3, 1)"
            }}>
              <div style={{
                background: "white",
                borderRadius: "12px",
                boxShadow: "0 8px 30px rgba(0,0,0,0.12), 0 0 1px rgba(0,0,0,0.2)",
                border: "1px solid #e5e7eb",
                padding: "16px",
                display: "flex",
                flexDirection: "column",
                gap: "12px",
                maxHeight: "260px",
                overflowY: "auto",
              }}>
                {/* What it CAN answer */}
                {activeDesignCTellsYou.length > 0 && (
                  <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                    <div style={{ fontSize: "13px", fontWeight: "600", color: "#2563eb" }}>This explanation can answer:</div>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: "6px" }}>
                      {activeDesignCTellsYou.map((q, idx) => {
                        const isClicked = clickedQuestions.has(q);
                        return (
                          <button
                            key={`tells-${idx}`}
                            onMouseDown={(e) => {
                              // Prevent input from losing focus when clicking a suggestion
                              e.preventDefault();
                              handleDesignCQuestion(q, "tellsYou");
                            }}
                            className="suggestion-btn"
                            style={{
                              textAlign: "left",
                              padding: "6px 12px",
                              fontSize: "12px",
                              borderRadius: "16px",
                              border: isClicked ? "1px solid #cbd5e1" : "1px solid #bfdbfe",
                              backgroundColor: isClicked ? "#f8fafc" : "#eff6ff",
                              color: isClicked ? "#9ca3af" : "#1e40af",
                              cursor: "pointer",
                              transition: "all 0.2s"
                            }}
                          >
                            {q}
                          </button>
                        )
                      })}
                    </div>
                  </div>
                )}

                {/* What it CANNOT answer */}
                {activeDesignCDoesntTellYou.length > 0 && (
                  <div style={{ display: "flex", flexDirection: "column", gap: "6px", marginTop: "4px" }}>
                    <div style={{ fontSize: "13px", fontWeight: "600", color: "#4b5563" }}>This explanation cannot answer:</div>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: "6px" }}>
                      {activeDesignCDoesntTellYou.map((q, idx) => {
                        const isClicked = clickedQuestions.has(q);
                        return (
                          <button
                            key={`doesnt-${idx}`}
                            onMouseDown={(e) => {
                              e.preventDefault();
                              handleDesignCQuestion(q, "doesntTellYou");
                            }}
                            className="suggestion-btn"
                            style={{
                              textAlign: "left",
                              padding: "6px 12px",
                              fontSize: "12px",
                              borderRadius: "16px",
                              border: isClicked ? "1px solid #cbd5e1" : "1px solid #e5e7eb",
                              backgroundColor: isClicked ? "#f8fafc" : "#f3f4f6",
                              color: isClicked ? "#9ca3af" : "#374151",
                              cursor: "pointer",
                              transition: "all 0.2s"
                            }}
                          >
                            {q}
                          </button>
                        )
                      })}
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Text Input Box */}
            <MessageInput disabled={busy} onSend={handleSend} />

            {/* Compact Qualtrics Progress Badge (Moved UNDER the input) */}
            <div style={{ display: "flex", justifyContent: "center", marginTop: "4px" }}>
              <div style={{
                display: "inline-flex",
                alignItems: "center",
                gap: "6px",
                padding: "4px 12px",
                backgroundColor: isRequirementMet ? "#f0fdf4" : "#fefce8",
                color: isRequirementMet ? "#166534" : "#b45309",
                borderRadius: "999px", // Pill shape
                fontSize: "12px",
                fontWeight: "600",
                border: `1px solid ${isRequirementMet ? "#bbf7d0" : "#fde68a"}`,
                boxShadow: "0 1px 2px rgba(0,0,0,0.05)"
              }}>
                {isRequirementMet ? (
                  <>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>
                    <span>Requirement met — you may proceed</span>
                  </>
                ) : (
                  <>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
                    <span>
                    {/* {!hasClickedAllDesignC
                        ? "Please click all suggested questions to continue"
                        : `Ask ${additionalQuestionsLeft} additional question${additionalQuestionsLeft !== 1 ? 's' : ''} to continue`
                      } */}
                      Ask {additionalQuestionsLeft} additional question{additionalQuestionsLeft !== 1 ? 's' : ''} to continue
                    </span>
                  </>
                )}
              </div>
            </div>

          </div>

        </div>

        <style>
          {`
          @keyframes fadePop {
            from { opacity: 0; transform: translateY(15px); }
            to { opacity: 1; transform: translateY(0); }
          }
          .suggestion-btn:hover { 
            background: #2563eb !important; 
            color: white !important; 
            border-color: #2563eb !important; 
          }
        `}
        </style>
      </div>
      {showManual && (
        <div
          style={{
            position: "fixed",
            top: 0, left: 0, right: 0, bottom: 0,
            backgroundColor: "rgba(0, 0, 0, 0.5)",
            zIndex: 9999,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            padding: "20px"
          }}
          onClick={() => setShowManual(false)} // Close if clicked outside
        >
          <div
            style={{
              backgroundColor: "white",
              borderRadius: "12px",
              padding: "30px",
              maxWidth: "600px",
              maxHeight: "80vh",
              overflowY: "auto",
              boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
              position: "relative"
            }}
            onClick={(e) => e.stopPropagation()} // Prevent clicking inside from closing it
          >
            {/* Close Button (X) */}
            <button
              onClick={() => setShowManual(false)}
              style={{
                position: "absolute", top: "16px", right: "16px",
                background: "none", border: "none", fontSize: "20px", cursor: "pointer", color: "#6b7280"
              }}
            >
              ✕
            </button>

            <div style={{
              backgroundColor: "#eff6ff",
              borderLeft: "4px solid #2563eb",
              padding: "12px 16px",
              borderRadius: "0 8px 8px 0",
              margin: "10px 0 24px 0"
            }}>
              <p style={{ fontSize: "15px", color: "#1e3a8a", margin: 0, fontWeight: 500 }}>
                Chat with the assistant to find out what information the displayed explanation can or cannot tell about the AI prediction.
              </p>
            </div>

            <h2 style={{ marginTop: 0, color: "#111827" }}>How to use this tool</h2>

            <div style={{ fontSize: "14px", color: "#374151", lineHeight: "1.6" }}>
              <h3 style={{ fontSize: "15px", marginTop: "20px", color: "#2563eb" }}>1. Applicant's Profile (Top Left)</h3>
              <p style={{ margin: "5px 0" }}>Displays the applicant's credit score (50 or above is approved) and the six factors that the AI system used to predict the applicant's score.</p>

              <table style={{ width: "100%", borderCollapse: "collapse", marginTop: "10px", fontSize: "13px", borderBottom: "1.5px solid gray" }}>
                <tbody>
                  <tr>
                    <td style={{ borderBottom: "1.5px solid gray", width: "38%", textAlign: "center", padding: "8px", fontWeight: "bold" }}>Factor</td>
                    <td style={{ borderBottom: "1.5px solid gray", width: "42%", textAlign: "left", padding: "8px", fontWeight: "bold" }}>Description</td>
                    <td style={{ borderBottom: "1.5px solid gray", width: "20%", padding: "8px", fontWeight: "bold" }}>Value range</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>Credit used (%)</td>
                    <td style={{ padding: "8px" }}>Percentage of the amount of available credit that they already used</td>
                    <td style={{ padding: "8px" }}>0-100%</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>Months since last credit application</td>
                    <td style={{ padding: "8px" }}>How long has passed (in months) since they last applied for credit</td>
                    <td style={{ padding: "8px" }}>0-48 months</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>On-time payment rate (%)</td>
                    <td style={{ padding: "8px" }}>Percentage of repayments made on time</td>
                    <td style={{ padding: "8px" }}>0-100%</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>Months since last late payment</td>
                    <td style={{ padding: "8px" }}>How long has passed (in months) since they last missed a payment</td>
                    <td style={{ padding: "8px" }}>0-96 months</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>Loans not paid off (%)</td>
                    <td style={{ padding: "8px" }}>Percentage of borrowing accounts with outstanding debt</td>
                    <td style={{ padding: "8px" }}>0-100%</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>Number of loans</td>
                    <td style={{ padding: "8px" }}>Number of loan accounts held in the past</td>
                    <td style={{ padding: "8px" }}>0-100</td>
                  </tr>
                </tbody>
              </table>

              <h3 style={{ fontSize: "15px", marginTop: "20px", color: "#2563eb" }}>2. Explanation Dashboard (Bottom Left)</h3>
              <p style={{ margin: "5px 0" }}>Displays one explanation chart explaining the AI's prediction.</p>

              <h3 style={{ fontSize: "15px", marginTop: "20px", color: "#2563eb" }}>3. Chatbot Assistant (Right)</h3>
              <p style={{ margin: "5px 0" }}>
                Ask the assistant about the explanation chart. <b>Tips:</b> click through the suggested questions to learn what the current explanation can and cannot answer. Ask {requiredQuestions} questions to proceed with the survey.
              </p>
              <p style={{ margin: "5px 0" }}>You can ask questions like:</p>
              <ul style={{ margin: "5px 0", paddingLeft: "20px" }}>
                <li>"Is this explanation limited to describing the AI's prediction for this particular applicant, or does it also show patterns valid across many other applicants?"</li>
                <li>"Does this explanation show which factors had the biggest impact on the applicant's current score?"</li>
                <li>"Can this explanation tell me which factor the AI considers the most important for all applicants?"</li>
                <li>"How would my score change if I had more credit used?"</li>
              </ul>
            </div>

            <button
              onClick={() => setShowManual(false)}
              style={{
                width: "100%", padding: "10px", marginTop: "25px",
                backgroundColor: "#2563eb", color: "white", border: "none", borderRadius: "8px", fontWeight: "bold", cursor: "pointer"
              }}
            >
              Got it
            </button>
          </div>
        </div>
      )}
    </div>
  )
}