import React, { useMemo, useState, useEffect, useRef } from 'react'
import MessageList from './MessageList.jsx'
import MessageInput from './MessageInput.jsx'
import { chatWithToolsStream } from '../api.js'
import InstanceEditor from './InstanceEditor.jsx'
import Dashboard from './Dashboard.jsx'

// What would you like to explore next?
const COVERAGE_QUESTIONS = {
  local: {
    tellsYou: [
      "What factors lowered/increased my score?",
      "How much did a factor affect my score?",
    ],
    doesntTellYou: [
      "What can I do to improve my score to 50?",
      "Which factors are generally important across all applicants?",
      "How would my score change if I have fewer loans?",
    ]
  },
  counterfactual: {
    tellsYou: [
      "What is the smallest change needed to get approved?",
    ],
    doesntTellYou: [
      "Why was my original score so low?",
      "Would decreasing my credit usage alone increase my score?",
      "Did my \"Loans not paid off\" negatively affect my score?"
    ]
  },
  global: {
    tellsYou: [
      "Which factors matter the most to the system in general?",
      "Does the system generally prioritise late payments or credit usage?",
    ],
    doesntTellYou: [
      "What changes should I make to increase my score?",
      "Why was my specific application denied?",
      "How much did \"credit used\" impact my score?",
    ]
  },
  cp: {
    tellsYou: [
      "What happens to my score if I change just one factor?",
      "How strongly does my score react to a specific factor?"
    ],
    doesntTellYou: [
      "Which factor affected my current score the most?",
      "Did a factor positively affect the score I got?",
      "What is the smallest change needed to get approved?",
    ]
  }
}

const DESIGN_C_QUESTIONS = {
  local: {
    tellsYou: [
      "Which factor had the biggest impact on the score I got?",
      "Did my credit used positively affect the score I got?",
    ],
    doesntTellYou: [
      "What can I do to improve my score to 50?",
      "Which factors are generally important across all applicants?",
      "How would my score change if I have more loans?",
    ]
  },
  cp: {
    tellsYou: [
      "How would my score change if I have more loans?",
      "How strongly does my score react to a specific factor?"
    ],
    doesntTellYou: [
      "Which factor had the biggest impact on the score I got?",
      "Did my credit used positively affect the score I got?",
      "For other applicants, does increasing on-time payment rate increases their score?",
    ]
  }
}

// Dictionary to unify explanation labels for both the System Prompt and the UI Prompts
const EXPLANATION_DICT = {
  local: {
    system: "Which factors pushed the applicant's score up or down. Generated by starting from a baseline score for the average applicant and attributing the difference between that baseline and this applicant's predicted score across the applicant's factors",
    ui: "What Affected Your Score",
    description: "how each factor influenced the score you got. Blue bars represent factors that increased the score. Red bars represent factors that decreased the score"
  },
  counterfactual: {
    system: "Smallest set of changes needed for this applicant to reach target score. Generated by searching for a nearby combination of factor changes that makes the model reach the target. This is not a ranking of feature importance or proof that unchanged factors do not matter.",
    ui: "How to Improve Your Score",
    description: "the smallest change you could make to reach the target score"
  },
  cp: {
    system: "How this applicant's predicted score will change when changing a single factor. Generated by keeping all other factor values fixed at the applicant's current values and repeatedly predicting the score at hypothetical values of the selected factor. It is not a local-importance chart: it cannot say whether the factor helped or hurt the current score, or rank it against other factors.",
    ui: "How Each Factor Affects Your Score",
    description: "how changing one factor at a time would change your score"
  },
  // global: {
  //   system: "Which factors matter the most across everyone",
  //   ui: "What Mattered Most Overall",
  //   description: "how important each factor is across all applicants"
  // },
}

// Helper to dynamically generate the welcome message based on the selected explanation
const generateWelcomeMessage = (explanationKey) => {
  if (!explanationKey) {
    return "The dashboard currently displays no explanation. Please select an explanation from the menu to begin.";
  }
  const info = EXPLANATION_DICT[explanationKey];
  return `The dashboard currently displays **${info.ui}**, which shows ${info.description}. Let me know if you have any questions.`;
};

// Helper to read initial explanation from URL parameters
const getInitialExplanation = () => {
  if (typeof window !== "undefined") {
    const params = new URLSearchParams(window.location.search);
    const exp = params.get("exp");
    if (exp && EXPLANATION_DICT[exp]) {
      return exp;
    }
  }
  return "local"; // Default to "What Affected Your Score"
};

// Helper to read the applicant instance ID from URL parameters
const getInitialInstanceId = () => {
  if (typeof window !== "undefined") {
    const params = new URLSearchParams(window.location.search);
    const id = params.get("id"); // e.g., ?id=58
    if (id && !isNaN(parseInt(id, 10))) {
      return parseInt(id, 10);
    }
  }
  return 12; // Default ID
};

const getParticipantId = () => {
  if (typeof window !== "undefined") {
    const params = new URLSearchParams(window.location.search);
    return params.get("pid") || "anonymous_user";
  }
  return "anonymous_user";
};

const getRequiredQuestions = () => {
  if (typeof window !== "undefined") {
    const params = new URLSearchParams(window.location.search);
    const req = params.get("req");
    if (req && !isNaN(parseInt(req, 10))) {
      return parseInt(req, 10);
    }
  }
  return 3;
};


export default function ChatPage() {
  // Initialize instance ID from URL
  const [userInstanceId] = useState(getInitialInstanceId())
  const [participantId] = useState(getParticipantId());
  const [requiredQuestions] = useState(getRequiredQuestions());
  const [showManual, setShowManual] = useState(false)
  const applicantNames = { 57: "Alex", 58: "Bob" };
  const applicantName = applicantNames[userInstanceId];
  const applicantReference = applicantName
    ? `applicant ID ${userInstanceId} (${applicantName})`
    : `applicant ID ${userInstanceId}`;

  // Set selected explanation from URL or default to 'local'
  const [selectedExplanation, setSelectedExplanation] = useState(getInitialExplanation())

  // Track whether the explanations menu is collapsed or expanded
  // const [showExplanationsMenu, setShowExplanationsMenu] = useState(true)

  // Track which Design C and Design B questions have been clicked
  const [clickedQuestions, setClickedQuestions] = useState(new Set())

  // Initialise with the welcome message of the starting explanation
  const [messages, setMessages] = useState([
    {
      role: 'assistant',
      content: generateWelcomeMessage(getInitialExplanation())
    }
  ])

  const [busy, setBusy] = useState(false)
  const [visualisations, setVisualisations] = useState([])
  const [counterfactualViz, setCounterfactualViz] = useState(null)
  const [cpVisualisations, setCpVisualisations] = useState([])
  const [backendHistory, setBackendHistory] = useState([])
  const [showSuggestions, setShowSuggestions] = useState(true)

  const activeDesign = "C" // Hardcoded to C as default

  // Dynamically compile Design C "tells you" questions 
  const activeDesignCTellsYou = useMemo(() => {
    if (!selectedExplanation || !DESIGN_C_QUESTIONS[selectedExplanation]?.tellsYou) return [];
    return DESIGN_C_QUESTIONS[selectedExplanation].tellsYou;
  }, [selectedExplanation]);

  // Dynamically compile Design C "doesn't tell you" questions 
  const activeDesignCDoesntTellYou = useMemo(() => {
    if (!selectedExplanation || !DESIGN_C_QUESTIONS[selectedExplanation]?.doesntTellYou) return [];
    return DESIGN_C_QUESTIONS[selectedExplanation].doesntTellYou;
  }, [selectedExplanation]);

  // --- QUALTRICS TRACKING LOGIC ---
  // 1. Identify all Design C questions for the current explanation
  const allRequiredQuestions = [...activeDesignCTellsYou, ...activeDesignCDoesntTellYou];

  // 2. Check if they clicked all of them
  const hasClickedAllDesignC = allRequiredQuestions.length > 0
    ? allRequiredQuestions.every(q => clickedQuestions.has(q))
    : true;

  // 3. Count ONLY messages that were NOT generated by clicking the buttons
  // (We do this by checking if the user message text includes the boilerplate prompt text)
  const manualMessageCount = messages.filter(m =>
    m.role === 'user' &&
    !m.content.includes("I chose the question:")
  ).length;

  const additionalQuestionsLeft = Math.max(0, requiredQuestions - manualMessageCount);

  // Both conditions must be satisfied
  const isRequirementMet = hasClickedAllDesignC && additionalQuestionsLeft === 0;

  useEffect(() => {
    // If embedded in an iframe (Qualtrics), send a message when requirement is met
    if (isRequirementMet) {
      window.parent.postMessage({ type: "CHAT_REQUIREMENT_MET" }, "*");
    }
  }, [isRequirementMet]);
  // ---------------------------------

  // Keep a ref of the selected explanation to safely access inside async callbacks
  const selectedExpRef = useRef(selectedExplanation)
  useEffect(() => {
    selectedExpRef.current = selectedExplanation
  }, [selectedExplanation])

  // Update the initial message if the user clicks/toggles dashboard explanations BEFORE asking a question
  /*
  useEffect(() => {
    setMessages(prev => {
      const hasUserMsg = prev.some(m => m.role === 'user');
      if (hasUserMsg) return prev;
      return [{ role: 'assistant', content: generateWelcomeMessage(selectedExplanation) }];
    });
  }, [selectedExplanation]);
  */

  // Start a new log session on initial page load / refresh
  useEffect(() => {
    // You can append the PID so your backend saves logs with the Prolific ID
    fetch(`http://127.0.0.1:5001/api/session/reset?pid=${participantId}`)
      .then(res => res.json())
      .then(data => console.log("Initial session started for:", participantId, data.log_file))
      .catch(err => console.error("Error starting session:", err));
  }, [participantId]);

  const visibleTexts = useMemo(() => {
    if (!selectedExplanation) {
      return {
        system: "No explanations currently visible",
        ui: "no explanation"
      }
    }
    return {
      system: EXPLANATION_DICT[selectedExplanation].system,
      ui: EXPLANATION_DICT[selectedExplanation].ui
    }
  }, [selectedExplanation])

  // The system prompt dynamically reads the current dashboard state.
  const system = useMemo(() => {
    return `You are a helpful assistant explaining a machine learning model used as an automated tool to approve or reject credit limit increase applications. The user represents ${applicantReference} in the dataset who applies to increase their credit limit and has no knowledge of AI. When answering questions, assume the user is asking about their own credit profile unless stated otherwise. The model produces a credit score from 0 to 100. A score of 50 or higher means the application is approved.

      The model considers these six factors/features:
      - Credit used (%) -- Percentage of available credit already used        
      - Months since last late payment -- How long since they last missed a payment
      - On-time payment rate (%) -- How often they've paid on time
      - Number of loans -- Number of loan accounts they've had
      - Loans not paid off (%) -- How many borrowing accounts still have debt on them
      - Months since last credit application -- How long since they last applied for credit
      
      Currently, the user only has the following explanation visible on the dashboard on the left: ${visibleTexts.ui} (${visibleTexts.system}). 
      If the user refers to “this explanation,” “the chart,” or “the figure,” they mean this specific visible panel. Tailor your response to what is shown here, and do not imply that any other tools are visible on the dashboard. 
      IMPORTANT: You do NOT automatically know the data behind it. You MUST call the corresponding tool(s) to retrieve the data for this visible explanation so you can accurately understand the outputs and answer the user's questions. 

      Guidelines:
      - Be concise. Use layperson-friendly language. Answer in less than 200 words.
      - AVOID ADDED ADVICE: Do not invent financial advice, guess missing values, or hallucinate results. Only describe relationships that are explicitly supported by the currently displayed explanation or by data returned from tools. If users ask for actions to take, describe in model's term.
      - If required inputs (e.g., factor name, target) are missing, ask the user to provide them.
      - Clearly distinguish between advice for a single applicant versus a broader pattern across applicants.
      - If the currently shown explanation can answer the user's question, MUST explicitly state that your answer is based on the chart shown in the dashboard. 
      - PROACTIVE TOOL CALLING & ASSUMPTION CORRECTION: If the user asks a question that the current visible explanation cannot answer, you MUST explain the cognitive mismatch before calling a new tool. 
        1. Identify the user's goal (e.g., "You are looking for what to change to improve your score...").
        2. Explain how the current chart is generated and why it cannot answer that question (e.g., "...but this chart is generated by comparing your past data to the average, not by testing hypothetical future changes, so it cannot provide advice on what to change").
        3. And MUST immediately call the correct tool to generate the appropriate explanation and explain the chart applied. Do not just tell the user another explanation is needed; generate it.`
  }, [userInstanceId, applicantReference, visibleTexts.system, visibleTexts.ui])

  async function handleSend(text) {
    if (!text?.trim()) return

    setShowSuggestions(false)

    const userMsg = { role: "user", content: text }
    setMessages(prev => [...prev, userMsg])

    // streaming
    setBusy(true)
    setMessages(prev => [...prev, { role: "assistant", content: "" }])

    chatWithToolsStream({
      message: text,
      history: backendHistory,
      system,
      options: { temperature: 1 },
      onToken: token => {
        setMessages(prev => {
          const copy = [...prev]
          const last = copy[copy.length - 1]
          if (last?.role === "assistant") {
            last.content += token
          }
          return copy
        })
      },
      onVisualisations: vizs => {
        if (!vizs?.length) return

        const counterfactuals = []
        const cpDashboardVizs = []
        const inlineVizes = []

        vizs.forEach(v => {
          const tool = v?.meta?.tool || v?.visualisation?.meta?.tool

          let vizType = "extra"
          if (tool === "get_counterfactual_explanation") vizType = "counterfactual"
          if (tool === "generate_shap_bar_plot" || tool === "generate_local_shap_bar_plot") vizType = "local"
          if (tool === "generate_shap_summary_plot") vizType = "global"

          // Separate single CP plots from the "All CP plots" view
          if (tool === "generate_all_cp_plots") vizType = "cp_dashboard"
          if (tool === "get_cp_plot") vizType = "single_cp_plot"

          if (vizType === "counterfactual") {
            counterfactuals.push(v)
          }
          else if (vizType === "cp_dashboard") {
            cpDashboardVizs.push(v)
          }

          // Determine what goes into the chat timeline (inline)
          if (
            vizType === "extra" ||
            vizType === "single_cp_plot" ||
            (vizType === "cp_dashboard" && selectedExpRef.current !== "cp") ||
            (vizType === "local" && selectedExpRef.current !== "local") ||
            (vizType === "global" && selectedExpRef.current !== "global") ||
            (vizType === "counterfactual" && selectedExpRef.current !== "counterfactual")
          ) {
            inlineVizes.push(v)
          }
        })

        if (counterfactuals.length > 0) {
          setCounterfactualViz(JSON.parse(JSON.stringify(counterfactuals[0])))
        }

        if (cpDashboardVizs.length > 0) {
          setCpVisualisations(cpDashboardVizs)
        }

        if (inlineVizes.length > 0) {
          setMessages(prev => {
            const copy = [...prev]
            const last = copy[copy.length - 1]
            if (last?.role === "assistant") {
              last.visualisations = last.visualisations
                ? [...last.visualisations, ...inlineVizes]
                : [...inlineVizes]
            }
            return copy
          })
        }
      },
      onDone: payload => {
        if (payload?.history) {
          setBackendHistory(payload.history)
        }
        setBusy(false)
      },
      onError: err => {
        setMessages(prev => [
          ...prev,
          {
            role: "assistant",
            content: `Error: ${JSON.stringify(err)}`,
          },
        ])
        setBusy(false)
      },
    })
  }

  const handleDesignCQuestion = (q, category) => {
    // Mark this exact question string as clicked
    setClickedQuestions(prev => new Set(prev).add(q))

    let promptText = ""
    if (category === "tellsYou") {
      promptText = `The explanation currently shown: ${visibleTexts.ui}. I chose the question: "${q}" under the category "This explanation CAN answer". Explain why the currently shown explanation can answer this question, and also tell me the answer.`
    } else {
      promptText = `The explanation currently shown: ${visibleTexts.ui}. I chose the question: "${q}" under the category "This explanation CANNOT answer". Explain why the currently shown explanation cannot answer this question, and use the appropriate tool to generate and show the explanation that CAN answer it.`
    }

    handleSend(promptText)
  }

  const showInitialSuggestions =
    showSuggestions &&
    !busy &&
    messages.filter(m => m.role === "user").length === 0

  /*
  // Only allow setting the selection if it is currently empty.
  const handleSelectExplanation = (key) => {
    if (!selectedExplanation) {
      setSelectedExplanation(key)
    }
  }

  // Calculate unclicked Design B options
  const unclickedDesignBOptions = activeDesignBOptions?.filter(opt => !clickedQuestions.has(opt)) || [];
  */

  return (
    <div style={{ display: "flex", gap: 12, height: "100%", padding: 12 }}>

      {/* Left side: Instance editor, Dashboard */}
      <div
        style={{
          flex: 0.4,
          display: "flex",
          flexDirection: "column",
          gap: 10,
          minWidth: 400,
          paddingRight: 4 // slight breathing room before the chat
        }}
      >
        {/* Invisible spacer to perfectly match the height of the right-side Info button container */}
        <div style={{ height: "16px", flexShrink: 0 }}></div>

        {/* Instance Editor */}
        <div
          style={{
            border: "1px solid #ddd",
            borderRadius: 8,
            background: "#fafafa",
            overflow: "auto",
          }}
        >
          <InstanceEditor instanceId={userInstanceId} />
        </div>

        {/* Dashboard Section */}
        <div
          style={{
            flex: 1,
            minHeight: 0,
            display: "flex",
            flexDirection: "column",
          }}
        >
          <div style={{ overflow: "auto", flex: 1 }}>
            <Dashboard
              instanceId={userInstanceId}
              visualisations={visualisations}
              counterfactualViz={counterfactualViz}
              cpVisualisations={cpVisualisations}
              selectedExplanation={selectedExplanation}
            />
          </div>
        </div>
      </div>

      {/* Right side: Chat */}
      <div
        style={{
          flex: 0.6,
          display: "flex",
          flexDirection: "column",
          gap: 6,
          position: "relative",
        }}
      >
        {/* Help Button above the Chat Container */}
        <div style={{ display: "flex", justifyContent: "flex-end", alignItems: "center", height: "20px", flexShrink: 0 }}>
          <button
            onClick={() => setShowManual(true)}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "4px",
              background: "#f3f4f6",
              border: "1px solid #e5e7eb",
              borderRadius: "16px",
              padding: "2px 8px",
              fontSize: "13px",
              color: "#4b5563",
              cursor: "pointer",
              fontWeight: 600,
            }}
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="10"></circle>
              <line x1="12" y1="16" x2="12" y2="12"></line>
              <line x1="12" y1="8" x2="12.01" y2="8"></line>
            </svg>
            Info
          </button>
        </div>


        {/* Floating Design Switcher Buttons */}
        {/* 
        {showInitialSuggestions && (
          <div
            style={{
              position: "absolute",
              top: -42,
              left: "50%",
              transform: "translateX(-50%)",
              display: "flex",
              gap: 8,
              zIndex: 20
            }}
          >
            {["A", "B", "C"].map((design) => (
              <button
                key={design}
                onClick={() => setActiveDesign(design)}
                style={{
                  padding: "6px 16px",
                  borderRadius: 20,
                  border: "1px solid #cbd5e1",
                  background: activeDesign === design ? "#2563eb" : "#f8fafc",
                  color: activeDesign === design ? "white" : "#334155",
                  cursor: "pointer",
                  fontSize: 13,
                  fontWeight: 600,
                  transition: "all 0.2s ease"
                }}
              >
                Design {design}
              </button>
            ))}
          </div>
        )}
        */}

        {/* Chat Container */}
        <div
          style={{
            border: "1px solid #ddd",
            borderRadius: 8,
            padding: 12,
            flex: 1,
            overflow: "auto",
            background: "white",
            position: "relative",
            display: "flex",
            flexDirection: "column"
          }}
        >
          {/* Main Message History */}
          <MessageList messages={messages} busy={busy} />

          {/* Persistent Box for Design C */}
          {activeDesign === "C" && !busy && selectedExplanation !== "" && (activeDesignCTellsYou.length > 0 || activeDesignCDoesntTellYou.length > 0) && (
            <div
              style={showInitialSuggestions ? {
                position: "absolute",
                top: 125,           /* Hard ceiling: box will NEVER go higher than 90px from the top */
                bottom: 20,        /* Pulls from the bottom so the margin can calculate the center */
                left: 0,
                right: 0,
                margin: "auto",    /* Magically centers the box vertically and horizontally */
                height: "fit-content", /* Required for vertical margin: auto to work */
                width: "80%",
                maxWidth: 450,
                background: "white",
                borderRadius: 16,
                boxShadow: "0 10px 30px rgba(0,0,0,0.12)",
                border: "1px solid #e5e7eb",
                padding: 24,
                display: "flex",
                flexDirection: "column",
                gap: 12,
                animation: "fadePop 0.4s ease forwards",
                zIndex: 10,
              } : {
                /* This is the state AFTER messages are sent - stays at the bottom naturally */
                width: "80%",
                maxWidth: 450,
                margin: "20px auto 0 auto",
                background: "white",
                borderRadius: 16,
                boxShadow: "0 4px 15px rgba(0,0,0,0.08)",
                border: "1px solid #e5e7eb",
                padding: 24,
                display: "flex",
                flexDirection: "column",
                gap: 12,
              }}
            >
              <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>

                {/* Category 1: What this tells you */}
                {activeDesignCTellsYou.length > 0 && (
                  <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                    <div style={{ fontWeight: 600, fontSize: 14, color: "#2563eb" }}>
                      This explanation can answer:
                    </div>
                    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                      {activeDesignCTellsYou.map((q, idx) => {
                        const isClicked = clickedQuestions.has(q);
                        return (
                          <div
                            key={idx}
                            onClick={() => handleDesignCQuestion(q, "tellsYou")}
                            className="suggestion-btn"
                            style={{
                              display: "flex",
                              alignItems: "flex-start",
                              gap: "12px",
                              textAlign: "left",
                              padding: "8px 16px",
                              color: isClicked ? "#9ca3af" : undefined,
                              backgroundColor: isClicked ? "#f8fafc" : "#f3f4f6"
                            }}
                          >
                            <div style={{ marginTop: "2px", flexShrink: 0 }}>
                              {isClicked ? (
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="#2563eb">
                                  <circle cx="12" cy="12" r="12" />
                                  <path d="M7 12.5l3 3 7-7" stroke="#ffffff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
                                </svg>
                              ) : (
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#cbd5e1" strokeWidth="2.5">
                                  <circle cx="12" cy="12" r="10" />
                                </svg>
                              )}
                            </div>
                            <span style={{ lineHeight: "1.4" }}>{q}</span>
                          </div>
                        )
                      })}
                    </div>
                  </div>
                )}

                {/* Category 2: What it doesn't tell you */}
                {activeDesignCDoesntTellYou.length > 0 && (
                  <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                    <div style={{ fontWeight: 600, fontSize: 14 }}>
                      This explanation cannot answer:
                    </div>
                    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                      {activeDesignCDoesntTellYou.map((q, idx) => {
                        const isClicked = clickedQuestions.has(q);
                        return (
                          <div
                            key={idx}
                            onClick={() => handleDesignCQuestion(q, "doesntTellYou")}
                            className="suggestion-btn"
                            style={{
                              display: "flex",
                              alignItems: "flex-start",
                              gap: "12px",
                              textAlign: "left",
                              padding: "8px 16px",
                              color: isClicked ? "#9ca3af" : undefined,
                              backgroundColor: isClicked ? "#f8fafc" : "#f3f4f6"
                            }}
                          >
                            <div style={{ marginTop: "2px", flexShrink: 0 }}>
                              {isClicked ? (
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="#2563eb">
                                  <circle cx="12" cy="12" r="12" />
                                  <path d="M7 12.5l3 3 7-7" stroke="#ffffff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
                                </svg>
                              ) : (
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#cbd5e1" strokeWidth="2.5">
                                  <circle cx="12" cy="12" r="10" />
                                </svg>
                              )}
                            </div>
                            <span style={{ lineHeight: "1.4" }}>{q}</span>
                          </div>
                        )
                      })}
                    </div>
                  </div>
                )}
                <div style={{ fontSize: 13, color: "#6b7280", textAlign: "center" }}>
                  Choose one to explore more, or ask any question.
                </div>
              </div>
            </div>
          )}

          {/* Persistent Box for Design B */}
          {/*
          {activeDesign === "B" && !busy && selectedExplanation !== "" && unclickedDesignBOptions.length > 0 && (
            <div
              style={showInitialSuggestions ? {
                position: "absolute",
                top: "50%",
                left: "50%",
                transform: "translate(-50%, -50%)",
                width: "80%",
                maxWidth: 450,
                background: "white",
                borderRadius: 16,
                boxShadow: "0 10px 30px rgba(0,0,0,0.12)",
                border: "1px solid #e5e7eb",
                padding: 24,
                display: "flex",
                flexDirection: "column",
                gap: 12,
                animation: "fadeSlide 0.4s ease forwards",
                zIndex: 10,
              } : {
                width: "80%",
                maxWidth: 450,
                margin: "20px auto 0 auto",
                background: "white",
                borderRadius: 16,
                boxShadow: "0 4px 15px rgba(0,0,0,0.08)",
                border: "1px solid #e5e7eb",
                padding: 24,
                display: "flex",
                flexDirection: "column",
                gap: 12,
              }}
            >
              {showInitialSuggestions ? (
                <>
                  <div style={{ fontWeight: 600, fontSize: 15, color: "#374151", textAlign: "center" }}>
                    {DESIGN_B_CONTENT.message}
                  </div>
                  <div style={{ fontSize: 14, color: "#4b5563", marginBottom: 8, textAlign: "center" }}>
                    {DESIGN_B_CONTENT.question}
                  </div>
                </>
              ) : (
                <div style={{ fontWeight: 600, fontSize: 15, color: "#374151", marginBottom: 4, textAlign: "center" }}>
                  What else do you think this explanation can tell you?
                </div>
              )}

              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                {unclickedDesignBOptions.map((opt, idx) => (
                  <div
                    key={idx}
                    onClick={() => {
                      setClickedQuestions(prev => new Set(prev).add(opt));
                      let promptText = \`The explanation currently shown is: \${visibleTexts.ui}. The question is asking: "\${showInitialSuggestions ? DESIGN_B_CONTENT.question : "What do you think this explanation can tell you?"}". My answer is: "\${opt}". Explain if I am correct or not. If incorrect, use the appropriate tool to generate and show which explanation can answer my question: "\${opt}".\`;
                      handleSend(promptText);
                    }}
                    className="suggestion-btn"
                  >
                    {opt}
                  </div>
                ))}
              </div>
            </div>
          )}
          */}

          {/* This spacer provides the empty room needed for the browser to scroll the latest message to the top */}
          <div style={{ height: "80vh", flexShrink: 0 }} />

        </div>

        {/* Input Area */}
        <div style={{ marginTop: 5, display: "flex", flexDirection: "column", gap: 8 }}>

          {/* Compact Qualtrics Progress Badge */}
          <div style={{ display: "flex", justifyContent: "center" }}>
            <div style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "6px",
              padding: "4px 12px",
              backgroundColor: isRequirementMet ? "#f0fdf4" : "#fefce8",
              color: isRequirementMet ? "#166534" : "#b45309",
              borderRadius: "999px", // Pill shape
              fontSize: "12px",
              fontWeight: "600",
              border: `1px solid ${isRequirementMet ? "#bbf7d0" : "#fde68a"}`,
              boxShadow: "0 1px 2px rgba(0,0,0,0.05)"
            }}>
              {isRequirementMet ? (
                <>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>
                  <span>Requirement met — you may proceed</span>
                </>
              ) : (
                <>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
                  <span>
                    {!hasClickedAllDesignC
                      ? "Please click all suggested questions above to continue"
                      : `Ask ${additionalQuestionsLeft} additional question${additionalQuestionsLeft !== 1 ? 's' : ''} to continue`
                    }
                  </span>
                </>
              )}
            </div>
          </div>

          <MessageInput disabled={busy} onSend={handleSend} />
        </div>

        <style>
          {`
          @keyframes fadePop {
            from { opacity: 0; transform: translateY(15px); }
            to { opacity: 1; transform: translateY(0); }
          }
          .suggestion-btn {
            padding: 10px 14px;
            border-radius: 8px;
            background: #f3f4f6;
            font-size: 13px;
            cursor: pointer;
            transition: all 0.2s ease;
            text-align: center;
          }
          .suggestion-btn:hover { background: #2563eb !important; color: white !important; }
        `}
        </style>
      </div>
      {showManual && (
        <div
          style={{
            position: "fixed",
            top: 0, left: 0, right: 0, bottom: 0,
            backgroundColor: "rgba(0, 0, 0, 0.5)",
            zIndex: 9999,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            padding: "20px"
          }}
          onClick={() => setShowManual(false)} // Close if clicked outside
        >
          <div
            style={{
              backgroundColor: "white",
              borderRadius: "12px",
              padding: "30px",
              maxWidth: "600px",
              maxHeight: "80vh",
              overflowY: "auto",
              boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
              position: "relative"
            }}
            onClick={(e) => e.stopPropagation()} // Prevent clicking inside from closing it
          >
            {/* Close Button (X) */}
            <button
              onClick={() => setShowManual(false)}
              style={{
                position: "absolute", top: "16px", right: "16px",
                background: "none", border: "none", fontSize: "20px", cursor: "pointer", color: "#6b7280"
              }}
            >
              ✕
            </button>

            <h2 style={{ marginTop: 0, color: "#111827" }}>Your task</h2>
            Chat with the assistant to find out what kinds of questions the displayed explanation can answer. Ak

            <h2 style={{ marginTop: 0, color: "#111827" }}>How to use this tool</h2>

            <div style={{ fontSize: "14px", color: "#374151", lineHeight: "1.6" }}>
              <h3 style={{ fontSize: "15px", marginTop: "20px", color: "#2563eb" }}>1. Your Applicant Profile (Top Left)</h3>
              <p style={{ margin: "5px 0" }}>Displays your credit score (50 or above is approved) and the six factors AI system used to evaluate the score.</p>

              <table style={{ width: "100%", borderCollapse: "collapse", marginTop: "10px", fontSize: "13px", borderBottom: "1.5px solid gray" }}>
                <tbody>
                  <tr>
                    <td style={{ borderBottom: "1.5px solid gray", width: "38%", textAlign: "center", padding: "8px", fontWeight: "bold" }}>Factor</td>
                    <td style={{ borderBottom: "1.5px solid gray", width: "42%", textAlign: "left", padding: "8px", fontWeight: "bold" }}>Description</td>
                    <td style={{ borderBottom: "1.5px solid gray", width: "20%", padding: "8px", fontWeight: "bold" }}>Value range</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>Credit used (%)</td>
                    <td style={{ padding: "8px" }}>Percentage of available credit already used</td>
                    <td style={{ padding: "8px" }}>0-100%</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>Months since last credit application</td>
                    <td style={{ padding: "8px" }}>How long since they last applied for credit</td>
                    <td style={{ padding: "8px" }}>0-48 months</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>On-time payment rate (%)</td>
                    <td style={{ padding: "8px" }}>How often they've paid on time</td>
                    <td style={{ padding: "8px" }}>0-100%</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>Months since last late payment</td>
                    <td style={{ padding: "8px" }}>How long since they last missed a payment</td>
                    <td style={{ padding: "8px" }}>0-96 months</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>Loans not paid off (%)</td>
                    <td style={{ padding: "8px" }}>How many borrowing accounts still have outstanding debts</td>
                    <td style={{ padding: "8px" }}>0-100%</td>
                  </tr>
                  <tr>
                    <td style={{ textAlign: "center", padding: "8px" }}>Number of loans</td>
                    <td style={{ padding: "8px" }}>Number of loan accounts they've had</td>
                    <td style={{ padding: "8px" }}>0-100</td>
                  </tr>
                </tbody>
              </table>

              <h3 style={{ fontSize: "15px", marginTop: "20px", color: "#2563eb" }}>2. Explanation Dashboard (Bottom Left)</h3>
              <p style={{ margin: "5px 0" }}>Displays one explanation chart explaining the AI's decision.</p>

              <h3 style={{ fontSize: "15px", marginTop: "20px", color: "#2563eb" }}>3. AI Assistant Chat (Right)</h3>
              <p style={{ margin: "5px 0" }}>Ask the assistant about your score. <b>To begin:</b> click through the suggested questions in the center menu to learn what the current chart can and cannot answer. Ask three more questions to proceed with the survey.
              You can ask questions like:
              - 
              </p>
            </div>

            <button
              onClick={() => setShowManual(false)}
              style={{
                width: "100%", padding: "10px", marginTop: "25px",
                backgroundColor: "#2563eb", color: "white", border: "none", borderRadius: "8px", fontWeight: "bold", cursor: "pointer"
              }}
            >
              Got it
            </button>
          </div>
        </div>
      )}
    </div>
  )
}